datasets:
  rxr_caption: # name of the dataset builder
    dataset_card: dataset_card/rxr_caption.md # path to the dataset card 
    data_type: images # [images|videos|features] we use features in this case for extracted video features 

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_train.json
          storage: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_train.json
        val:
          url: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_val.json
          storage: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_val.json
        test:
          url: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_test.json
          storage: /workspace1/fpcattan/Landmark-RxR/filtered_LandmarkRxR_test.json
      images:
        storage: /workspace1/fpcattan/Matterport3D/ # path a las imagenes